# Generated by Django 4.1.1 on 2022-10-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_apply_job_alter_job_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='cover_letter',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='email',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='website',
        ),
        migrations.AddField(
            model_name='apply',
            name='Password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apply',
            name='Password_confirmation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apply',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.TextField(max_length=500),
        ),
        migrations.AddField(
            model_name='apply',
            name='Email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
