# Generated by Django 4.1.1 on 2022-10-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_tybe_job_location_alter_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Description',
            field=models.TextField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
