# Generated by Django 4.1.1 on 2022-10-24 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='owner',
        ),
    ]
